/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Dimensions} from 'react-native';
import BloomVideo, {VideoStreaming} from 'react-native-bloom-video';

const {width, height} = Dimensions.get('window');

console.log(width, height);

// BloomVideo.init('ba0063bfbc1a5ad878')
//   .then((res) => {
//     // BloomAd.showSplash();
//     console.log('init', res);
//   })
//   .catch((error) => {
//     // console.log(error);
//   });

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
  };
  componentDidMount() {}
  render() {
    return (
      <View style={styles.container}>
        <VideoStreaming
          appId="ba0063bfbc1a5ad878"
          style={{
            width: width,
            height: height,
            backgroundColor: 'blue',
          }}
          onChange={(params) => {
            console.log('params', params);
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'red',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
